# Generated by Django 3.2.3 on 2021-06-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='idnum',
            field=models.CharField(max_length=20),
        ),
    ]
