# Generated by Django 3.2.3 on 2021-06-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_airport_flight_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_day',
            field=models.DateField(default='2012-09-04', verbose_name='到达日期'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='idnum',
            field=models.CharField(max_length=20, verbose_name='乘机人身份证号'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=20, verbose_name='乘机人姓名'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='telnum',
            field=models.CharField(max_length=40, verbose_name='乘机人联系电话'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.ManyToManyField(to='app02.User', verbose_name='乘机人对应用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=40, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idnum',
            field=models.CharField(max_length=40, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telnum',
            field=models.CharField(max_length=20, unique=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=20, unique=True, verbose_name='账号'),
        ),
    ]
